version: '3.8'

services:
  node:
    image: node:latest
    container_name: node_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm start"]
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
      - CHOKIDAR_USEPOLLING=1  # Enables hot reload in Docker
      - WATCHPACK_POLLING=true  # Alternative for Webpack
